### ISSUE TITLE
Enlaces rotos página principal..

### ISSUE THREAD

**Issue by rje1974** [ROS-Spanish-Users-Group/ros2_documentation#10]
Hola @fmrico , entiendo que la pagina principal tienen los enlaces rotos. 

Hay algo que pueda hacer para ayudar..?
Saludos..

![image](https://user-images.githubusercontent.com/4406802/212169925-b9ab8fdc-b15e-4339-bae2-218f51d24831.png)

**Comment by fmrico** [comment]
Buenas!!

Sí, los enlaces no está consolidados aún, esperando a ver cómo nos van a enlazar. 

la url provisional es https://ros-spanish-users-group.github.io/ros2_documentation/rolling/index.html

Si quieres ayudar, abre un issue con alguna página para traducir :wink: 

Saludos!!

**Comment by rje1974** [comment]
Ok @fmrico , hay un documento de como colaborar con este proyecto que pueda leer..? Porque posiblemente si no existe lo mejor sea comenzar por hacer ese.. Por otro lado.. Cual es la direccion del servidor de discord..?

**Comment by jsduenass** [comment]
@rje1974 la documentación original de ROS2 tiene una [guía de como contribuir a la documentación](https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.html) 
cosas que restaltar: 
* [como configurar el sistema y crear la pagina local y La necesidad de hacer pruebas](https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.html#headings) 
*  [El manejo de titulos en reStructured ](https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.html#headings) importante en esta parte de traducción.
