### ISSUE TITLE
Translate  /The-ROS2-Project/Contributing/

### ISSUE THREAD

**Issue by jsduenass** [ROS-Spanish-Users-Group/ros2_documentation#11]
Hola  
Yo inicialmente me propongo a realizar la traducción de las siguientes paginas en Rolling

- [x] [Contributing-To-ROS-2-Documentation.rst](https://github.com/ROS-Spanish-Users-Group/ros2_documentation/blob/rolling/source/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.rst)
- [x] [Windows-Tips-and-Tricks.rst](https://github.com/ROS-Spanish-Users-Group/ros2_documentation/blob/rolling/source/The-ROS2-Project/Contributing/Windows-Tips-and-Tricks.rst)
- [x] [Code-Style-Language-Versions.rst](https://github.com/ROS-Spanish-Users-Group/ros2_documentation/blob/rolling/source/The-ROS2-Project/Contributing/Code-Style-Language-Versions.rst)

Dejando pendiente las siguientes paguinas por si alguien más quiere colaborar e ir adelantando
- [ ] [Build-Farms.rst](https://github.com/ROS-Spanish-Users-Group/ros2_documentation/blob/rolling/source/The-ROS2-Project/Contributing/Build-Farms.rst)
- [ ] [Migration-Guide-Python.rst  ](https://github.com/ROS-Spanish-Users-Group/ros2_documentation/blob/rolling/source/The-ROS2-Project/Contributing/Migration-Guide-Python.rst )
- [ ] [Quality-Guide.rst](https://github.com/ROS-Spanish-Users-Group/ros2_documentation/blob/rolling/source/The-ROS2-Project/Contributing/Quality-Guide.rst)
- [ ] [Developer-Guide.rst](https://github.com/ROS-Spanish-Users-Group/ros2_documentation/blob/rolling/source/The-ROS2-Project/Contributing/Developer-Guide.rst)
- [ ] [Migration-Guide.rst ](https://github.com/ROS-Spanish-Users-Group/ros2_documentation/blob/rolling/source/The-ROS2-Project/Contributing/Migration-Guide.rst )

**Comment by fmrico** [comment]
Se ha hecho ya el merge, así que podemos cerrar este isse.
