### ISSUE TITLE
Tutorials Demos Page Translation

### ISSUE THREAD

**Issue by Juancams** [ROS-Spanish-Users-Group/ros2_documentation#3]
Buenas!

Voy a empezar con la traducción de estás [páginas](https://github.com/Juancams/ros2_documentation/tree/rolling/source/Tutorials/Demos) a lo largo de estos días. Si alguien tiene interes que no dude en comentarlo por aquí y poder repartirnos el trabajo ^^

- [x] [Content-Filtering-Subscription.rst](https://github.com/Juancams/ros2_documentation/blob/rolling/source/Tutorials/Demos/Content-Filtering-Subscription.rst)
- [x] [Intra-Process-Communication.rst](https://github.com/Juancams/ros2_documentation/blob/rolling/source/Tutorials/Demos/Intra-Process-Communication.rst)
- [X] [Logging-and-logger-configuration.rst](https://github.com/Juancams/ros2_documentation/blob/rolling/source/Tutorials/Demos/Logging-and-logger-configuration.rst)
- [X] [Managed-Nodes.rst](https://github.com/Juancams/ros2_documentation/blob/rolling/source/Tutorials/Demos/Managed-Nodes.rst)
- [X] [Quality-of-Service.rst](https://github.com/Juancams/ros2_documentation/blob/rolling/source/Tutorials/Demos/Quality-of-Service.rst)
- [X] [Real-Time-Programming.rst](https://github.com/Juancams/ros2_documentation/blob/rolling/source/Tutorials/Demos/Real-Time-Programming.rst)
- [X] [Rosbag-with-ROS1-Bridge.rst](https://github.com/Juancams/ros2_documentation/blob/rolling/source/Tutorials/Demos/Rosbag-with-ROS1-Bridge.rst)
- [X] [dummy-robot-demo.rst](https://github.com/Juancams/ros2_documentation/blob/rolling/source/Tutorials/Demos/dummy-robot-demo.rst)

Mucho ánimo a tod@s.

**Comment by Mecb1407** [comment]
Hola Juancmas como vas? Te puedo colaborar en la traducción de algunas de estás paginas? No dudes en contactarme si necesitas alguna ayuda

**Comment by Juancams** [comment]
Buenas!

Me quedán esas 3 páginas sin marcar y revisión general. Me iba a poner este fin de semana pero si te quieres encargar tu no hay problema.

**Comment by Mecb1407** [comment]
Perfecto Juan, este fin de semana te puedo ayudar con la terminación de la traducción de las paginas restantes. Saludos.

**Comment by fmrico** [comment]
Buenas, ¿como vais con esto?

**Comment by Juancams** [comment]
Hago los commits esta noche, me queda revisar 2 páginas.
