### ISSUE TITLE
Beginner CLI Tools Translation - part 0

### ISSUE THREAD

**Issue by MartinNievas** [ROS-Spanish-Users-Group/ros2_documentation#5]
Buenas :)

Estaré realizando la traducción de estas  [páginas](https://github.com/MartinNievas/ros2_documentation/tree/translation_tutorial_begginer_cli_pt0/source/Tutorials/Beginner-CLI-Tools) a lo largo de estos días. Por el momento, en este issue solo las que están aquí debajo:

- [x] [Introducing-Turtlesim](https://github.com/MartinNievas/ros2_documentation/blob/translation_tutorial_begginer_cli_pt0/source/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.rst)
- [x] [Understanding-ROS2-Nodes](https://github.com/MartinNievas/ros2_documentation/blob/translation_tutorial_begginer_cli_pt0/source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Nodes/Understanding-ROS2-Nodes.rst)
- [x] [Understanding-ROS2-Topics](https://github.com/MartinNievas/ros2_documentation/blob/translation_tutorial_begginer_cli_pt0/source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.rst)
- [x] [Understanding-ROS2-Parameters](https://github.com/MartinNievas/ros2_documentation/blob/translation_tutorial_begginer_cli_pt0/source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Parameters/Understanding-ROS2-Parameters.rst)
- [x] Revisar sintaxis (usted->tú)

Éxitos a tod@s

**Comment by MartinNievas** [comment]
Tengo unas dudas respecto a las traducciones en español de las imágenes/animaciones,
![Nodes-TopicandService](https://user-images.githubusercontent.com/24465803/209903360-441a17f6-c1dc-402b-a01b-b5eab3b59d1c.png)
que dependen de unas palabras que habría que coincidir en la traducción:
- Topic: Temas (acá en nuestro laboratorio le decimos "tópicos")
- Publisher: Publicador
- Subscriber: Suscriptor

**Comment by fmrico** [comment]
Hola @MartinNievas 

Mi opinión para una primera traducción:
* Topic -> Topic
* Publisher -> Publicador
* Subscriber -> Suscriptor

Muchas gracias!!

**Comment by fmrico** [comment]
Hola (again)

He creado este wiki para ir poniendo los convenios: https://github.com/ROS-Spanish-Users-Group/ros2_documentation/wiki

Saludos

**Comment by orensbruli** [comment]
> Hola (again)
> 
> He creado este wiki para ir poniendo los convenios: https://github.com/ROS-Spanish-Users-Group/ros2_documentation/wiki
> 
> Saludos

Puede ser interesante enlazar a la WIKI en el readme principal?

**Comment by fmrico** [comment]
Me parece buena idea :)

**Comment by orensbruli** [comment]
> Me parece buena idea :)

https://github.com/ROS-Spanish-Users-Group/ros2_documentation/pull/24
